export const CITIES = [
  "Akron, OH",
  "Albany, NY",
  "Albuquerque, NM",
  "Alexandria, VA",
  "Allentown, PA",
  "Amarillo, TX",
  "Anaheim, CA",
  "Anchorage, AK",
  "Ann Arbor, MI",
  "Arlington, TX",
  "Arlington, VA",
  "Asheville, NC",
  "Atlanta, GA",
  "Augusta, GA",
  "Aurora, CO",
  "Austin, TX",
  "Bakersfield, CA",
  "Baltimore, MD",
  "Baton Rouge, LA",
  "Billings, MT",
  "Birmingham, AL",
  "Boise, ID",
  "Boston, MA",
  "Boulder, CO",
  "Bridgeport, CT",
  "Brownsville, TX",
  "Buffalo, NY",
  "Cape Coral, FL",
  "Cedar Rapids, IA",
  "Chandler, AZ",
  "Charleston, SC",
  "Charlotte, NC",
  "Chattanooga, TN",
  "Chesapeake, VA",
  "Chicago, IL",
  "Cincinnati, OH",
  "Clarksville, TN",
  "Cleveland, OH",
  "Colorado Springs, CO",
  "Columbia, SC",
  "Columbus, GA",
  "Columbus, OH",
  "Corpus Christi, TX",
  "Dallas, TX",
  "Davenport, IA",
  "Dayton, OH",
  "Denver, CO",
  "Des Moines, IA",
  "Detroit, MI",
  "Durham, NC",
  "El Paso, TX",
  "Eugene, OR",
  "Evansville, IN",
  "Fayetteville, AR",
  "Fayetteville, NC",
  "Fort Collins, CO",
  "Fort Lauderdale, FL",
  "Fort Wayne, IN",
  "Fort Worth, TX",
  "Fresno, CA",
  "Frisco, TX",
  "Gilbert, AZ",
  "Glendale, AZ",
  "Grand Rapids, MI",
  "Green Bay, WI",
  "Greensboro, NC",
  "Greenville, SC",
  "Hartford, CT",
  "Henderson, NV",
  "Hialeah, FL",
  "Honolulu, HI",
  "Houston, TX",
  "Huntsville, AL",
  "Indianapolis, IN",
  "Irvine, CA",
  "Irving, TX",
  "Jackson, MS",
  "Jacksonville, FL",
  "Jersey City, NJ",
  "Kansas City, KS",
  "Kansas City, MO",
  "Knoxville, TN",
  "Lakeland, FL",
  "Lancaster, PA",
  "Lansing, MI",
  "Laredo, TX",
  "Las Vegas, NV",
  "Lexington, KY",
  "Lincoln, NE",
  "Little Rock, AR",
  "Long Beach, CA",
  "Los Angeles, CA",
  "Louisville, KY",
  "Lubbock, TX",
  "Madison, WI",
  "McAllen, TX",
  "McKinney, TX",
  "Memphis, TN",
  "Mesa, AZ",
  "Miami, FL",
  "Milwaukee, WI",
  "Minneapolis, MN",
  "Mobile, AL",
  "Modesto, CA",
  "Montgomery, AL",
  "Moreno Valley, CA",
  "Murfreesboro, TN",
  "Myrtle Beach, SC",
  "Naples, FL",
  "Nashville, TN",
  "New Haven, CT",
  "New Orleans, LA",
  "New York, NY",
  "Newark, NJ",
  "Newport News, VA",
  "Norfolk, VA",
  "North Las Vegas, NV",
  "Oakland, CA",
  "Oceanside, CA",
  "Oklahoma City, OK",
  "Omaha, NE",
  "Ontario, CA",
  "Orlando, FL",
  "Overland Park, KS",
  "Oxnard, CA",
  "Palm Bay, FL",
  "Panama City, FL",
  "Pasadena, CA",
  "Pasadena, TX",
  "Paterson, NJ",
  "Pembroke Pines, FL",
  "Pensacola, FL",
  "Peoria, IL",
  "Philadelphia, PA",
  "Phoenix, AZ",
  "Pittsburgh, PA",
  "Plano, TX",
  "Portland, ME",
  "Portland, OR",
  "Providence, RI",
  "Provo, UT",
  "Raleigh, NC",
  "Rancho Cucamonga, CA",
  "Reno, NV",
  "Richmond, VA",
  "Riverside, CA",
  "Rochester, NY",
  "Rockford, IL",
  "Sacramento, CA",
  "Salem, OR",
  "Salt Lake City, UT",
  "San Antonio, TX",
  "San Bernardino, CA",
  "San Diego, CA",
  "San Francisco, CA",
  "San Jose, CA",
  "Santa Ana, CA",
  "Santa Clarita, CA",
  "Santa Rosa, CA",
  "Savannah, GA",
  "Scottsdale, AZ",
  "Seattle, WA",
  "Shreveport, LA",
  "Sioux Falls, SD",
  "South Bend, IN",
  "Spokane, WA",
  "Springfield, IL",
  "Springfield, MO",
  "Springfield, MA",
  "St. Louis, MO",
  "St. Paul, MN",
  "St. Petersburg, FL",
  "Stamford, CT",
  "Stockton, CA",
  "Syracuse, NY",
  "Tacoma, WA",
  "Tallahassee, FL",
  "Tampa, FL",
  "Tempe, AZ",
  "Toledo, OH",
  "Topeka, KS",
  "Tucson, AZ",
  "Tulsa, OK",
  "Tyler, TX",
  "Virginia Beach, VA",
  "Waco, TX",
  "Washington, DC",
  "West Palm Beach, FL",
  "Wichita, KS",
  "Wilmington, NC",
  "Winston-Salem, NC",
  "Worcester, MA",
  "Yonkers, NY",
] as const;
