import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy | Truss",
  description:
    "How Truss collects, uses, and protects your data. We collect only what helps you get booked or find crew.",
};

export default function PrivacyPage() {
  return (
    <main className="max-w-3xl mx-auto px-4 sm:px-6 py-12">
      <div className="mb-10">
        <Link
          href="/"
          className="inline-block font-heading text-sm font-semibold tracking-widest uppercase text-signal-orange hover:text-orange-400 transition-colors mb-6"
        >
          Truss
        </Link>
        <h1 className="font-heading text-3xl sm:text-4xl font-bold tracking-wide uppercase leading-tight mb-2">
          Privacy <span className="text-signal-orange">Policy</span>
        </h1>
        <p className="text-sm text-aluminum">Last updated: February 2026</p>
      </div>

      {/* ── Plain-language summary ─────────── */}
      <section className="bg-deep-stage border border-white/5 rounded-lg p-5 mb-10">
        <h2 className="font-heading text-sm font-bold tracking-wider uppercase mb-2">
          The Short Version
        </h2>
        <ul className="space-y-2 text-sm text-aluminum leading-relaxed">
          <li className="flex items-start gap-2">
            <span className="text-signal-orange/40 mt-1.5 text-[6px]">●</span>
            We collect only what&apos;s needed to run the marketplace and help you get booked or find crew.
          </li>
          <li className="flex items-start gap-2">
            <span className="text-signal-orange/40 mt-1.5 text-[6px]">●</span>
            We never sell your personal data to anyone.
          </li>
          <li className="flex items-start gap-2">
            <span className="text-signal-orange/40 mt-1.5 text-[6px]">●</span>
            We don&apos;t run targeted advertising or build ad profiles on you.
          </li>
          <li className="flex items-start gap-2">
            <span className="text-signal-orange/40 mt-1.5 text-[6px]">●</span>
            We use aggregate market data (rates, demand by skill/city) to build tools that help the industry. Individual data is never exposed.
          </li>
          <li className="flex items-start gap-2">
            <span className="text-signal-orange/40 mt-1.5 text-[6px]">●</span>
            You can request a full export or deletion of your data at any time.
          </li>
        </ul>
      </section>

      <div className="space-y-10">
        {/* 1 */}
        <Section title="1. Who We Are">
          <P>
            Truss is operated by Truss Technologies LLC, based in San Francisco, California. When this policy says &quot;Truss,&quot; &quot;we,&quot; or &quot;us,&quot; it refers to Truss Technologies LLC.
          </P>
        </Section>

        {/* 2 */}
        <Section title="2. What We Collect and Why">
          <P>We collect data in three categories. Here&apos;s exactly what each one includes and what we use it for.</P>

          <Subsection title="Account information (you provide this)">
            <DataTable
              rows={[
                { data: "Name, email, phone", why: "Create your account, send booking notifications, allow producers/techs to contact you through the platform" },
                { data: "City", why: "Show you in relevant local search results" },
                { data: "Company name (producers)", why: "Display on your profile and invoices" },
                { data: "Password", why: "Stored as a secure hash by Supabase Auth. We never see or store your actual password." },
              ]}
            />
          </Subsection>

          <Subsection title="Profile information (you provide this)">
            <DataTable
              rows={[
                { data: "Skills, specializations, gear list", why: "Match you with relevant job opportunities and let producers search for specific expertise" },
                { data: "Hourly rates (per skill)", why: "Auto-fill booking requests, power the rate guide to help the industry understand fair market rates" },
                { data: "Bio, experience level, portfolio photos", why: "Display on your public profile so producers can evaluate fit" },
                { data: "Insurance status (self-reported)", why: "Let producers filter by insured technicians. We do not verify this information." },
                { data: "Availability calendar", why: "Let producers see when you're free and filter search by date" },
                { data: "Profile photo", why: "Display on your profile. Stored in Supabase Storage." },
              ]}
            />
          </Subsection>

          <Subsection title="Platform activity (generated by usage)">
            <DataTable
              rows={[
                { data: "Booking history (projects, roles, rates, hours, status)", why: "Track your gig history, calculate earnings, power the reputation system" },
                { data: "Reviews and ratings", why: "Build trust between techs and producers. Reviews are public." },
                { data: "Messages", why: "Enable communication between producers and techs. Messages are private to participants." },
                { data: "Profile views (count only)", why: "Show techs how visible their profile is. We track view counts, not who specifically viewed you." },
                { data: "Referral data", why: "Track who referred whom to credit referral bonuses" },
                { data: "Notifications", why: "Deliver in-app alerts about bookings, reviews, and reminders" },
              ]}
            />
          </Subsection>
        </Section>

        {/* 3 */}
        <Section title="3. What We Don't Collect">
          <ul className="space-y-1.5 ml-4">
            {[
              "We don't track your location in real time or in the background",
              "We don't read your contacts, camera, microphone, or files",
              "We don't collect biometric data",
              "We don't build behavioral profiles for advertising",
              "We don't buy data about you from third-party brokers",
              "We don't use dark patterns to extract more data than necessary",
            ].map((item, i) => (
              <li key={i} className="text-sm text-aluminum leading-relaxed flex items-start gap-2">
                <span className="text-signal-orange/40 mt-1.5 text-[6px]">●</span>
                {item}
              </li>
            ))}
          </ul>
        </Section>

        {/* 4 */}
        <Section title="4. How We Use Aggregate Data">
          <P>
            We use anonymized, aggregate data from the platform to build industry tools — like the rate guide at <Link href="/rates" className="text-signal-orange hover:underline">/rates</Link>. This data helps technicians understand what their skills are worth in different markets and helps producers budget accurately.
          </P>
          <P>
            Aggregate means: &quot;A1 engineers in San Francisco average $65-85/hr across 47 bookings.&quot; It never means: &quot;Marcus Rodriguez charged $75/hr on this specific booking.&quot; Individual rates, bookings, and earnings are never exposed publicly or shared with third parties.
          </P>
          <P>
            We believe this market transparency is good for workers. Historically, rate information in the AV industry has been opaque, which disadvantages technicians in negotiations. Making aggregate rate data public helps level that playing field.
          </P>
        </Section>

        {/* 5 */}
        <Section title="5. Third-Party Services">
          <P>We use a small number of third-party services to operate the platform. Each one receives only the data it needs.</P>
          <DataTable
            rows={[
              { data: "Supabase", why: "Database, authentication, and file storage. Hosts all platform data. SOC 2 Type II compliant." },
              { data: "Stripe", why: "Payment processing. Handles credit card information directly — we never see or store card numbers." },
              { data: "Resend", why: "Transactional email delivery (booking confirmations, reminders). Receives only email address and message content." },
              { data: "Google Analytics", why: "Anonymous page-view analytics to understand which pages are useful. No personally identifiable information is sent." },
              { data: "Vercel", why: "Website hosting. Processes web requests but does not store user data." },
            ]}
          />
          <P>
            We do not use any advertising networks, data brokers, or tracking pixels beyond Google Analytics. We do not participate in cross-site tracking.
          </P>
        </Section>

        {/* 6 */}
        <Section title="6. Data Sharing">
          <P>We share your data only in these specific situations:</P>
          <ul className="space-y-1.5 ml-4 mb-3">
            {[
              "With other users, as part of normal platform use (your public profile is visible to logged-in producers; your messages are visible to conversation participants; your reviews are public)",
              "With Stripe, to process payments you initiate",
              "With Resend, to deliver emails triggered by your activity",
              "If required by law, court order, or legal process",
              "To protect the safety of our users or the public",
            ].map((item, i) => (
              <li key={i} className="text-sm text-aluminum leading-relaxed flex items-start gap-2">
                <span className="text-signal-orange/40 mt-1.5 text-[6px]">●</span>
                {item}
              </li>
            ))}
          </ul>
          <P>
            We have never sold user data and will never sell user data. If Truss is acquired, this policy transfers to the acquiring entity and your data protections remain in effect.
          </P>
        </Section>

        {/* 7 */}
        <Section title="7. Data Security">
          <P>
            All data is transmitted over HTTPS. Database access is protected by Row Level Security policies that ensure users can only read and write their own data. Authentication is handled by Supabase Auth with secure password hashing. API routes that perform system operations use a separate service-role client with restricted access.
          </P>
          <P>
            Payment information is handled entirely by Stripe and never touches our servers.
          </P>
        </Section>

        {/* 8 */}
        <Section title="8. Data Retention">
          <P>
            We retain your data for as long as your account is active. If you delete your account, we will delete your personal data within 30 days. Some data may be retained in anonymized, aggregate form (e.g., booking volume statistics) that cannot be linked back to you.
          </P>
          <P>
            Booking and payment records may be retained for up to 7 years as required by tax and financial regulations.
          </P>
        </Section>

        {/* 9 */}
        <Section title="9. Your Rights">
          <P>You have the right to:</P>
          <ul className="space-y-1.5 ml-4 mb-3">
            {[
              "Access — Request a full export of all data we hold about you",
              "Correction — Update or correct any inaccurate information through your profile settings or by contacting us",
              "Deletion — Request that we delete your account and all associated personal data",
              "Portability — Receive your data in a standard, machine-readable format",
              "Objection — Opt out of any non-essential data processing",
            ].map((item, i) => (
              <li key={i} className="text-sm text-aluminum leading-relaxed flex items-start gap-2">
                <span className="text-signal-orange/40 mt-1.5 text-[6px]">●</span>
                {item}
              </li>
            ))}
          </ul>
          <P>
            To exercise any of these rights, email <a href="mailto:hello@trusswork.org" className="text-signal-orange hover:underline">hello@trusswork.org</a>. We will respond within 30 days.
          </P>
        </Section>

        {/* 10 */}
        <Section title="10. California Privacy Rights">
          <P>
            If you are a California resident, you have additional rights under the California Consumer Privacy Act (CCPA). You have the right to know what personal information we collect, request deletion of that information, and opt out of the sale of personal information. Since we do not sell personal information, there is nothing to opt out of.
          </P>
          <P>
            We will not discriminate against you for exercising your privacy rights.
          </P>
        </Section>

        {/* 11 */}
        <Section title="11. Children">
          <P>
            Truss is not intended for anyone under 18. We do not knowingly collect data from minors. If we learn that we have collected data from someone under 18, we will delete it immediately.
          </P>
        </Section>

        {/* 12 */}
        <Section title="12. Cookies">
          <P>
            We use only essential cookies required for authentication (keeping you logged in). We do not use advertising cookies, tracking cookies, or cookie-based retargeting. Google Analytics uses a first-party cookie to distinguish unique visitors — this does not track you across other websites.
          </P>
        </Section>

        {/* 13 */}
        <Section title="13. Changes to This Policy">
          <P>
            If we make material changes to this policy, we will notify you by email and post a notice on the platform at least 14 days before the changes take effect. We will never retroactively reduce your privacy protections without your explicit consent.
          </P>
        </Section>

        {/* 14 */}
        <Section title="14. Contact">
          <P>Questions about this privacy policy or your data:</P>
          <div className="text-sm text-aluminum">
            <a href="mailto:hello@trusswork.org" className="text-signal-orange hover:underline">
              hello@trusswork.org
            </a>
          </div>
        </Section>
      </div>

      <footer className="mt-12 pt-6 border-t border-ink/[0.06] text-center">
        <p className="text-xs text-aluminum/50">
          &copy; 2026 Truss Technologies LLC. All rights reserved.
        </p>
        <div className="flex justify-center gap-4 mt-3">
          <Link href="/terms" className="text-xs text-aluminum/60 hover:text-signal-orange transition-colors">
            Terms of Service
          </Link>
          <Link href="/" className="text-xs text-aluminum/60 hover:text-signal-orange transition-colors">
            trusswork.org
          </Link>
        </div>
      </footer>
    </main>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section>
      <h2 className="font-heading text-base font-bold tracking-wider uppercase mb-3">
        {title}
      </h2>
      {children}
    </section>
  );
}

function Subsection({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="mb-4">
      <h3 className="text-sm font-semibold text-house-lights/80 mb-2">{title}</h3>
      {children}
    </div>
  );
}

function P({ children }: { children: React.ReactNode }) {
  return <p className="text-sm text-aluminum leading-relaxed mb-3">{children}</p>;
}

function DataTable({ rows }: { rows: { data: string; why: string }[] }) {
  return (
    <div className="overflow-x-auto mb-3">
      <table className="w-full text-sm border-collapse">
        <thead>
          <tr className="border-b border-ink/[0.06]">
            <th className="text-left py-2 pr-4 font-mono text-[10px] text-aluminum/65 tracking-widest uppercase">
              Data
            </th>
            <th className="text-left py-2 font-mono text-[10px] text-aluminum/65 tracking-widest uppercase">
              Why
            </th>
          </tr>
        </thead>
        <tbody>
          {rows.map((row, i) => (
            <tr key={i} className="border-b border-ink/[0.03]">
              <td className="py-2.5 pr-4 text-house-lights/80 align-top whitespace-nowrap">
                {row.data}
              </td>
              <td className="py-2.5 text-aluminum leading-relaxed">
                {row.why}
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}
